import datetime
import os
import json
import qrcode
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter


# helper function to create data record including pack_serial, bms_serial, and cell_data
def create_data_record(pack_serial, bms_serial, cell_data):
    return {
        "pack_serial": pack_serial,
        "bms_serial": bms_serial,
        "cells": cell_data,
        "timestamp": str(datetime.datetime.now())
    }


# function to generate the pdf certificate given the data record and pdf_filename
def create_pdf_certificate(record, pdf_filename):

    c = canvas.Canvas(pdf_filename, pagesize=letter)
    width, height = letter

    # Company logo and contact information
    logo_path = "images/Vaulta inside white badge trasnparent background.png"
    if os.path.exists(logo_path):
        c.drawImage(logo_path, 72, height - 100, width=60, height=60)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(140, height - 60, "Battery Passport")
    c.setFont("Helvetica", 10)
    c.drawString(140, height - 80, "Vaulta | info@vaulta.com.au | +61 412577911 | 53 Holland Street, Northgate QLD 4013")

    # required data information
    c.setFont("Helvetica", 12)
    c.drawString(72, height - 130, f"Pack Serial: {record['pack_serial']}")
    c.drawString(72, height - 150, f"BMS Serial: {record['bms_serial']}")
    c.drawString(72, height - 170, f"Timestamp: {record['timestamp']}")

    # the cell serial table
    c.setFont("Helvetica-Bold", 12)
    c.drawString(72, height - 200, "Cell Information:")

    data = [["Serial", "Production Date", "Production City", "Manufacturers", "Model Codes"]]
    for cell in record["cells"]:
        data.append([
            cell['serial'],
            cell["production_date"],
            cell["production_city"],
            cell["manufacturers"],
            cell["model_codes"]
        ])

    table = Table(data, colWidths=[160, 80, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.black),
    ]))

    table.wrapOn(c, width, height)
    table.drawOn(c, 72, height - 250 - (len(data) * 15))

    # the qr code, but only include the pack serial
    qr = qrcode.make(record["pack_serial"])
    qr_path = "temp_qr.png"
    qr.save(qr_path)
    c.drawImage(qr_path, width - 150, 72, width=100, height=100)
    os.remove(qr_path)

    # sign
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(72, 60, "This certificate was generated by Michael Zhang.")

    c.save()
    print(f"PDF passport created: {pdf_filename}")


# function to create both json and pdf file of the digital certificate
def create_digital_certificate(record):
    cert_identifier = "CERT_" + record["pack_serial"]
    json_filename = f"certificates/battery_passport_{record['pack_serial']}.json"
    with open(json_filename, 'w') as json_file:
        json.dump(record, json_file, indent=4)
    print(f"JSON certificate created: {json_filename}")

    pdf_filename = f"certificates/battery_passport_{record['pack_serial']}.pdf"
    create_pdf_certificate(record, pdf_filename)
    return cert_identifier, pdf_filename
