import datetime
import os
import json
import qrcode
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter


def create_data_record(pack_serial, bms_serial, cell_data):
    return {
        "PackSerial": pack_serial,
        "BMSSerial": bms_serial,
        "CellData": cell_data,
        "Timestamp": str(datetime.datetime.now())
    }


def create_pdf_certificate(record, pdf_filename):

    c = canvas.Canvas(pdf_filename, pagesize=letter)
    width, height = letter

    logo_path = "images/Vaulta inside white badge trasnparent background.png"
    if os.path.exists(logo_path):
        c.drawImage(logo_path, 72, height - 100, width=60, height=60)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(140, height - 60, "Battery Passport")
    c.setFont("Helvetica", 10)
    c.drawString(140, height - 80, "Vaulta | info@vaulta.com.au | +61 412577911 | 53 Holland Street, Northgate QLD 4013")

    c.setFont("Helvetica", 12)
    c.drawString(72, height - 130, f"Pack Serial: {record['PackSerial']}")
    c.drawString(72, height - 150, f"BMS Serial: {record['BMSSerial']}")
    c.drawString(72, height - 170, f"Timestamp: {record['Timestamp']}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(72, height - 200, "Cell Information:")

    data = [["Serial", "Production Date", "Production City"]]
    for cell in record["CellData"]:
        data.append([cell['serial'], cell["production_date"], cell["production_city"]])

    table = Table(data, colWidths=[200, 120, 120])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.black),
    ]))

    table.wrapOn(c, width, height)
    table.drawOn(c, 72, height - 250 - (len(data) * 15))

    qr = qrcode.make(record["PackSerial"])
    qr_path = "temp_qr.png"
    qr.save(qr_path)
    c.drawImage(qr_path, width - 150, 72, width=100, height=100)
    os.remove(qr_path)

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(72, 60, "This certificate was generated by Michael Zhang.")

    c.save()
    print(f"PDF passport created: {pdf_filename}")


def create_digital_certificate(record):
    cert_identifier = "CERT_" + record["PackSerial"]
    json_filename = f"certificates/battery_passport_{record['PackSerial']}.json"
    with open(json_filename, 'w') as json_file:
        json.dump(record, json_file, indent=4)
    print(f"JSON certificate created: {json_filename}")

    pdf_filename = f"certificates/battery_passport_{record['PackSerial']}.pdf"
    create_pdf_certificate(record, pdf_filename)
    return cert_identifier
